from appJar import gui
import keys
from hashlib import sha256
import binascii

key = 0

get_function = {
			"DES":keys.des(),
			"Blowfish":keys.blowfish(),
			"AES128":keys.aes(128),
			"AES192":keys.aes(192),
			"AES256":keys.aes(256),
			"CAST":keys.cast(),
			"RC2":keys.rc2(),
			"RC5":keys.rc5(),
			"Twofish":keys.twofish(),
			"IDEA":keys.idea(),
			"GOST28147":keys.gost28147()
			}

def hashKey(btn):
	sha = sha256(str(key).encode('utf-8')).hexdigest()
	print(sha)
	app.label(sha)

def get(btn):
	algorythm = app.getOptionBox("algorythm")
	if algorythm == "DES":
		key, time = keys.des()
	elif algorythm == "Blowfish":
		key, time = keys.blowfish()
	elif algorythm == "AES128":
		key, time = keys.aes(128)
	elif algorythm == "AES256":
		key, time = keys.aes(256)
	elif algorythm == "AES192":
		key, time = keys.aes(192)
	elif algorythm == "CAST":
		key, time = keys.cast()
	elif algorythm == "RC2":
		key, time = keys.rc2()
	elif algorythm == "IDEA":
		key, time = keys.idea()
	elif algorythm == "Twofish":
		key, time = keys.twofish()
	elif algorythm == "RC5":
		key, time = keys.rc5()
	elif algorythm == "GOST28147":
		key, time = keys.gost28147()

	message_save = "Key from algorythm " + algorythm + ":\n" + key + "\nDo you want to save it?"
	message_hash = "Key from algorythm " + algorythm + ":\n" + key +  "\nHash it?"
	if key != 0:
		hash_key = app.questionBox("Key", message_hash, parent=None)
		if hash_key:
			sha = sha256(str(key).encode('utf-8')).hexdigest()
			message_save = "Key from algorythm " + algorythm + ":\n" + key + "\nHash of it:\n" + sha +"\nDo you want to save it?"
		save = app.questionBox("Your key", message_save, parent=None)
		if save:
			f = open("key.txt", "a+")
			f.write("Key: " + key + " generated by " + algorythm + " algorythm\n")
			if hash_key:
				f.write("Hash of key is:\n" + sha + '\n')
			f.close()
			app.infoBox("save key", "Key was succsesfully saved to the file \"key.txt\"", parent=None)


def info(btn):
	app.addTable("info",
    			[["Algorythm", "Example of key", "Key length", "Time of generation\nby ansi x9.17"]])
	for algorythm in get_function :
		key, time = get_function[algorythm]
		app.addTableRows("info",
						[[algorythm, key, str(len(key)) + " bytes", str(time) + " ms"]])


with gui("Simple application for key generation", "800x500", font={'size':20, 'family':"Courier"}, bg="gray")as app:
	app.label("Welcome to the key generation app\nChoose an algorythm for key generation:")
	app.addLabelOptionBox("algorythm", ["DES", "Blowfish", "Twofish", "AES128", "AES192",
                        "AES256", "CAST", "RC2", "RC5", "IDEA", "GOST28147"])
	app.addButton("GET", get)
	app.addButton("Information about all algorythm", info)


