from appJar import gui
import keys

get_function = {
			"DES":keys.des(),
			"Blowfish":keys.blowfish(),
			"AES128":keys.aes(128),
			"AES192":keys.aes(192),
			"AES256":keys.aes(256),
			"CAST":keys.cast(),
			"RC2":keys.rc2(),
			}

def get(btn):
	algorythm = app.getOptionBox("algorythm")
	key = 0
	if algorythm == "DES":
		key, time = keys.des()
	elif algorythm == "Blowfish":
		key, time = keys.blowfish()
	elif algorythm == "AES128":
		key, time = keys.aes(128)
	elif algorythm == "AES256":
		key, time = keys.aes(256)
	elif algorythm == "AES192":
		key, time = keys.aes(192)
	elif algorythm == "CAST":
		key, time = keys.cast()
	elif algorythm == "RC2":
		key, time = keys.rc2()

	message = "Key from algorythm:\n" + key + "\nDo you want to save it?"
	if key != 0:
		save = app.questionBox("Your key", message, parent=None)
		if save:
			f = open("key.txt", "a+")
			f.write("Key: " + key + " generated by " + algorythm + " algorythm\n")
			f.close()
			app.infoBox("save key", "Key was succsesfully saved to the file \"key.txt\"", parent=None)


def info(btn):
	app.addTable("info",
    			[["Algorythm", "Example of key", "Key length", "Time of generation\nby ansi x9.17"]])
	for algorythm in get_function :
		key, time = get_function[algorythm]
		app.addTableRows("info",
						[[algorythm, key, str(len(key)) + " bytes", str(time) + " ms"]])


with gui("Simple application for key generation", "800x500", font={'size':20, 'family':"Courier"}, bg = "gray" ) as app:
	app.label("Welcome to the key generation app\nChoose an algorythm for key generation:")
	app.addLabelOptionBox("algorythm", ["DES", "Blowfish", "AES128", "AES192",
                        "AES256", "CAST", "RC2"])
	app.addButton("GET", get)
	app.addButton("Information about all algorythm", info)

